FROM cernide/cli

LABEL maintainer="Robin Röper <rr@linux.com>"

# Set service type
ENV POLYAXON_SERVICE=agent

# Reset to root
USER root

# Install the package
RUN pip install --no-cache-dir dist/*.whl[k8s_async]

# Set the user
RUN groupadd -r nobody && useradd -r -g nobody nobody
USER nobody

# Set the entrypoint
ENTRYPOINT ["polyaxon", "agent", "start"]