FROM cernide/cli

LABEL maintainer="Robin Röper <rr@linux.com>"

# Set service type
ENV POLYAXON_SERVICE=init

# Reset to root
USER root

# Install the package
RUN pip install --no-cache-dir dist/*.whl[fs,init]

# Set the user
RUN groupadd -r nobody && useradd -r -g nobody nobody
USER nobody

# Set the entrypoint
ENTRYPOINT ["polyaxon", "init", "--uuid=$RUN_UUID", "--kind=$RUN_KIND"]